使用try catch抛出异常时，方法需要调用异常函数

public MySqlPacket resolvePacket(TcpPacket tcp) throws Exception{



方法调用是一个压栈的过程，从调用的方法中返回就是一个弹栈的过程

你在A方法中调用了B方法，那么在方法栈中先压入A方法的栈帧，然后再压入B方法的栈帧，然后B如果正常返回，那么B的栈帧会弹出，只剩下A的，
A继续执行，如果B执行过程中遇到异常，并且没有捕获，就从有异常发生的地方开始抛，首先抛到A调用B的地方，
如果A也没有捕获，那么就继续抛，A调用B之后的代码也不会执行，然后再抛出到调用A方法的方法里，这样一直往外抛；

throw异常后不会往下执行，包括return；但会执行finally